import Head from 'next/head';
import Image from 'next/image';

import { TodoList, todoListEndElementId } from 'ui';

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo list</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main className='flex flex-col items-center justify-center flex-1 overflow-hidden'>
        <h1 className='w-full my-6 text-2xl text-center lg:my-16 lg:text-4xl'>
          Welcome!
        </h1>

        <TodoList className='max-w-lg' />
      </main>

      <footer id={todoListEndElementId} className='py-4 text-center lg:py-8'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
          className='inline-block'
        >
          Powered by{' '}
          <span className='inline-block ml-4 align-middle'>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
